+incdir+../uvm-1.1a/src
../uvm-1.1a/src/uvm.sv
../uvm-1.1a/src/dpi/uvm_dpi.cc

+incdir+../labs/lab08-b 
../labs/lab08-b/tb.sv
../labs/lab08-b/agent_config.sv
../labs/lab08-b/env_config.sv
../labs/lab08-b/dut_interface.sv
../labs/lab08-b/router.sv
../labs/lab08-b/my_transaction.sv
../labs/lab08-b/my_transaction_da3.sv
../labs/lab08-b/my_reference_model.sv
../labs/lab08-b/my_driver.sv
../labs/lab08-b/my_monitor.sv
../labs/lab08-b/my_sequence.sv
../labs/lab08-b/master_agent.sv
../labs/lab08-b/my_env.sv
../labs/lab08-b/my_test.sv
