+incdir+../uvm-1.1a/src
../uvm-1.1a/src/uvm.sv
../uvm-1.1a/src/dpi/uvm_dpi.cc

+incdir+../labs/lab11 
../labs/lab11/tb.sv
../labs/lab11/agent_config.sv
../labs/lab11/env_config.sv
../labs/lab11/dut_interface.sv
../labs/lab11/router.sv
../labs/lab11/my_transaction.sv
../labs/lab11/my_transaction_da3.sv
../labs/lab11/my_reference_model.sv
../labs/lab11/my_scoreboard.sv
../labs/lab11/driver_base_callback.sv
../labs/lab11/driver_error_callback.sv
../labs/lab11/driver_info_callback.sv
../labs/lab11/my_driver.sv
../labs/lab11/out_monitor.sv
../labs/lab11/my_monitor.sv
../labs/lab11/my_sequence.sv
../labs/lab11/my_sequence_lib.sv
../labs/lab11/da3_sequence.sv
//../labs/lab11/sa6_sequence.sv
//../labs/lab11/sa6_da3_sequence.sv
../labs/lab11/master_agent.sv
../labs/lab11/slave_agent.sv
../labs/lab11/my_env.sv
../labs/lab11/my_test.sv
../labs/lab11/my_test_driver_callback.sv
