+incdir+../uvm-1.1a/src
../uvm-1.1a/src/uvm.sv
../uvm-1.1a/src/dpi/uvm_dpi.cc

+incdir+../labs/lab11-b 
../labs/lab11-b/tb.sv
../labs/lab11-b/agent_config.sv
../labs/lab11-b/env_config.sv
../labs/lab11-b/dut_interface.sv
../labs/lab11-b/router.sv
../labs/lab11-b/my_transaction.sv
../labs/lab11-b/my_transaction_da3.sv
../labs/lab11-b/my_reference_model.sv
../labs/lab11-b/my_scoreboard.sv
../labs/lab11-b/driver_base_callback.sv
../labs/lab11-b/driver_error_callback.sv
../labs/lab11-b/driver_info_callback.sv
../labs/lab11-b/my_driver.sv
../labs/lab11-b/out_monitor.sv
../labs/lab11-b/my_monitor.sv
../labs/lab11-b/my_sequence.sv
../labs/lab11-b/my_sequence_lib.sv
../labs/lab11-b/da3_sequence.sv
../labs/lab11-b/sa6_sequence.sv
../labs/lab11-b/sa6_da3_sequence.sv
../labs/lab11-b/master_agent.sv
../labs/lab11-b/slave_agent.sv
../labs/lab11-b/my_env.sv
../labs/lab11-b/my_test.sv
../labs/lab11-b/my_test_driver_callback.sv
